framework:
    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        app: cache.adapter.redis_taggable
        default_redis_provider: redis://localhost:6379

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache: ~

services:
    cache.adapter.redis_taggable:
        class: Symfony\Component\Cache\Adapter\RedisTagAwareAdapter
        parent: cache.adapter.redis
        # Example using Predis as provider in dsn: redis://localhost:6379?class=\Predis\Client
        tags: { name: cache.pool, clearer: cache.app_clearer, provider: 'redis://localhost:6379' }
